apiVersion: v2
name: jupyter-dapla
description: The JupyterLab IDE with Python, tailored for SSB's data platform (Dapla).
icon: https://raw.githubusercontent.com/statisticsnorway/dapla-lab-helm-charts-services/d881cef65161a7209ac7c85fbcb6608581249dc1/icons/jupyter.png
keywords:
  - Jupyter
  - Python
home: https://jupyter.org/
sources:
# A chart can be either an 'application' or a 'library' chart.
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-services
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.5.3

dependencies:
  - name: library-chart
    version: 3.2.2
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-services
